name: CI/CD Pipeline for Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --------------------------------------
  # JOB 1: BUILD AND TEST
  # --------------------------------------
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  # --------------------------------------
  # JOB 2: DOCKER BUILD AND PUBLISH
  # --------------------------------------
  docker-build-and-publish:
    runs-on: ubuntu-latest
    needs: build-and-test  # Waits until build-and-test is successful

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file : ./DockerFile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
          ${{ secrets.DOCKER_USERNAME }}/flasktest-app:${{ github.sha }}

    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  # --------------------------------------
  # JOB 3: DEPLOY TO AWS EKS
  # --------------------------------------
  deploy:
    needs: docker-build-and-publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0'

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Check cluster access
      run: kubectl get nodes

    # Ensure the namespace exists
    - name: Ensure namespace exists
      run: kubectl create namespace flask-app || echo "Namespace flask-app already exists"

    - name: Replace image tag in deployment file
      run: |
        sed -i "s|flasktest-app:latest|flasktest-app:${{ github.sha }}|g" deployment.yaml

    - name: Deploy to EKS
      run: kubectl apply -f deployment.yaml

    - name: Restart deployment to pull the latest image
      run: kubectl rollout restart deployment flask-app -n flask-app
