name: CI/CD Pipeline for Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  docker-build-and-publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set dynamic image tag
      id: set-tag
      run: echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./DockerFile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.set-tag.outputs.tag }}

  deploy:
    needs: docker-build-and-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install envsubst
      run: sudo apt-get install -y gettext

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0'

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Prepare deployment file with updated image tag
      env:
        IMAGE_TAG: ${{ needs.docker-build-and-publish.outputs.image-tag }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        envsubst < deployment-template.yaml > deployment.yaml

    - name: Apply deployment
      run: |
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/flask-app -n flask-app 
